### ISSUE TITLE
request: translation possibility

### ISSUE THREAD

**Issue by ZahraMousavi** [bulib/primo-explore-bu#12]
Hi there. Thanks for sharing your packages with others. I work at Royal Danish library and here we of course need both Danish and English language options. We use your help menu package. We have added some extra lines to our main.js, so it chooses the right language for the help menu and passes the right list_of_elements to the helpMenuConfig. However we still cannot use your package directly because of one single string hard-coded in your code which we need it to be translatable as well, namely, 'Search help menu'.
Could you ever think of putting this string off the package or use translatable labels for that purpose so the package is translatable?

**Comment by atla5** [comment]
Hello! Our pleasure, we're very pleased it can be of use to you and your patrons!

I'm not sure how to implement a **"translatable label"** for this, though that would likely be the best option. _How you do that_ at the Royal Danish Library? 

Barring that option/in the immediate short term, we have a couple other things we could do:

1. we could add an additional customization option (variable) for that title string you mentioned that would be specified once and always show up like that (like the `logToConsole`)
2. add an implementable _function_ as a configuration option that you could implement that would determine that text whenever that component was loaded (like the `logEventToAnalytics`)
3. look into the `$scope` to find an alternative title out there in the ether that you can inject without specifying it inside of `helpMenuConfig`.

My initial preference is for 1, but I'm interested in your thoughts on what's best for your use case.

**Comment by ZahraMousavi** [comment]
Hello Aidan and thanks a lot for your time and consideration!

Well, we try to use back-office labels for every text we have, for example in our templates we use {{'fulldisplay.searchtip.box.title' | translate}} instead of a hard coded text, so admins can change the texts without the need for changing in the code.

But I think in this case, the best solution, as you suggested, is the first solution, so it is in sync with other variables in your package.

**Comment by atla5** [comment]
If I'm understanding you correctly, there's a way that I can access variables specified in the back office from within my templates in the customization package? I'm actually unaware of this feature. Could you send me a link to an example or documentation on that?

I just want to make sure that option 1 actually addresses your issue. I suspect we'd have to go with option 2 if you want to be able to display the title in more than one language.

**Comment by ZahraMousavi** [comment]
Yes, that's correct. 

They describe how to create or update a label in this address: https://knowledge.exlibrisgroup.com/Primo/Product_Documentation/Primo/New_Primo_User_Interface/New_UI_Customization_-_Best_Practices#Adding_the_Help_Link_to_the_UI

And then using the labels is as easy as calling them like this in the template without regard to how many language/languages you are are using in your view: {{'fulldisplay.searchtip.box.title' | translate}}

I guess you should be using option 1, because you only have a string, but I will be using option 2 in our main.js. As long as it doesn't come from inside the package it is manageable. If you have a look at our [main.js](https://github.com/Det-Kongelige-Bibliotek/KB-Primo-VE/blob/master/js/main.js), I am already using a function for list_of_elements, maybe it is not the best option, but it works as we want it :-)

**Comment by atla5** [comment]
Thank you for that. That seems very useful. 

Yeah, I can definitely implement that for you and push out a new version (`1.2.0`) shortly. 👍 

Would you be able to test it on your end sometime next week?

**Comment by ZahraMousavi** [comment]
Great! Yes, I will happily test it :-)

**Comment by atla5** [comment]
I wasn't able to get anything working in the back office, so I went with option 1.

The a new version ([`1.2.1`](https://www.npmjs.com/package/primo-explore-help-menu)) has been published, and a [pull request](https://github.com/bulib/primo-explore-bu/pull/16) has been created for your approval. 

The variable name to be added to the config is `helpMenuTitle`.

**Comment by ZahraMousavi** [comment]
Good job! It works perfectly 👍 
The only thing I could see was that it is not included in the sample .main.js (I used it before as a working example to see how to use and set the config options).
Thanks a lot for your time and effort :-)

**Comment by atla5** [comment]
Great catch. I've updated the `.main.js` and I'm glad to hear that it was helpful to include to begin with.

Our pleasure. We're glad to be of use! If you have any more ideas, requests, or general feedback about the package we'd love to stay in touch. We're especially interested in the usage analytics and whether those are working for you (when `publishEvents` is set to `true`).
