### ISSUE TITLE
question: primo-studio - Unable to get Primo Studio Addon to work

### ISSUE THREAD

**Issue by scott-oit** [bulib/primo-explore-bu#21]
I'm fairly knew to Primo so I'm assuming the problem is me.

In Primo Studio, I've tried loading our information and using the default. Install the addon and use my email as prompted. It seems to install correctly, but I'm not able to see the "Available in unpaywall" after any of the "Open Access" documents. Do I need to use the NPM method to install the addon? If so, do you have anytips on how to do that with a hosted environment?

Thanks for any help!

**Comment by atla5** [comment]
Hello! **Pleasure to meet you** and thanks for your interest.

**It's not you**. We've had some trouble getting the Primo Studio stuff to properly execute with each of them, but I'm very happy you found us here and filed an issue! 🙂 

I'd be more than happy to **walk you through setting up** via the npm method if you're free **sometime tomorrow afternoon** (2019-12-20). I work in the Eastern Timezone, but my day tomorrow is pretty open meeting-wise and I'm flexible. If that doesn't work we can set something up in early January.

Below are some **steps** if you want to get a head start (and everything works out 🤞). If you get stuck at all, don't worry, we can step through it over [chat](https://gitter.im/bulib/developers). It seems much more complicated than it is, and I found you can get used to it pretty quickly.

## Setting up the Primo Development Environment

1. Visit and download ExLibris's [`primo-explore-devenv`](https://github.com/ExLibrisGroup/primo-explore-devenv) (download is in the top right)
![screenshot of where you go to download the zip](https://user-images.githubusercontent.com/5565284/71221115-50d99980-2299-11ea-91c5-02424e3e12a4.png)
2. Follow the [installation instructions](https://github.com/ExLibrisGroup/primo-explore-devenv#installation) in their README
3. Make sure you remember to update the variables to the ones for your institution (mentioned in the README)


## Adding the Unpaywall Package to the Fresh Environment
1. run `npm install --save primo-explore-unpaywall` inside your view directory
2. create a `main.js` file inside of the `js` directory (`primo-explore/VIEW_NAME/custom/js/main.js`) and add in the code you see in the [`packages/unpaywall/src/.main.js`](https://github.com/bulib/primo-explore-bu/blob/master/packages/unpaywall/src/.main.js) file of this repo
3. try running `gulp run --browserify --view=VIEW_NAME`.
4. open up the browser and hit the local url ('http://localhost:8003/primo-explore/search?vid=VIEW_NAME') and search for "unpaywall". 

at this point there _should_ be a top result listed that says "the rise and rise of unpaywall" (at least how our's is configured). if everything's working properly, the link _should_ show up right on the results page. 

## Re-Adding Your Institutions Customizations from the Zip File
- go to where you normally upload/download your customizations in the back office (i can grab a link for you tomorrow, but you can also do this from inside Primo Studio, too, i think)
- download and unzip that file and copy and paste the contents of each subdirectory of `primo-explore/custom/` into their respective folders in your project code
- rerun `gulp run --browserify --view=YOUR_VIEW_NAME` and open it up in the browser to check.

**Comment by scott-oit** [comment]
Wow, thanks! These instructions look detailed enough I'm sure I can work through it. I'm off tomorrow, but I'll work through this Monday. I'll post if I have any questions.
Thanks again.

**Comment by atla5** [comment]
my pleasure. best of luck!

**Comment by atla5** [comment]
Checking back in after Christmas break, did everything work out alright? 

Also, if you wouldn't mind, would you share the institution you work for with us, either here or in an email to aidans@bu.edu?

**Comment by scott-oit** [comment]
I was able to get it working, but I haven't had a chance to replicate it to the sandbox. I'm still on vacation, I will pick this up Monday. Feel free to close this.
I work for Oregon Tech.
https://www.oit.edu/
https://alliance-primo.hosted.exlibrisgroup.com/primo-explore/search?sortby=rank&vid=OIT&lang=en_US

Thanks again for your help! You guys are awesome.

**Comment by atla5** [comment]
Happy to hear that it worked out and glad we could be of help! :beers:

**Comment by scott-oit** [comment]
I might have spoken too soon. I have it working on my machine, but I'm having troubles packaging it. If I download our package, I can add the addon, copy it to the packages folder, and run it. I'm able to zip it, upload it, and deploy the changes (I'm not sure if this step is necessary). However, the addon doesn't appear there.

I've also tried using the 'gulp create-package' command, but that removes my main.js and the addon.js and replaces it with a custom.js.

Do you have any advice? Thanks in advance!

**Comment by atla5** [comment]
### Potential Fix

my suspicion is that you're missing the `--browserify` tag when running the `create-package` command.

try running the following and then uploading the resulting `.zip` file.
```bash
$ gulp create-package --view=VIEW_NAME --browserify
```

### Explanation

the `primo-explore-devenv` provides two methods for bundling the javascript. 

without the `--browserify` it just concatenates any files with a `.js` extension in that `js/` directory (i think) and creates a `custom.js` file. it doesn't know about anything in the `node_modules/` directory, so it's not able to read the `primo-explore-unpaywall` dependency you've `npm install`-ed.

_with_ that `--browserify` extension, it uses the imports and dependencies in `main.js` (with references to the `npm` packages in `node_modules`) to create the `custom.js` and `custom.js.map`.

**Comment by scott-oit** [comment]
Thank you. It seems like that has the same result. I still have a custom.js, but that's it. Uploading doesn't work.

The ExLibris instructions say to use Node 6.9.2. Are you running a newer version?

**Comment by atla5** [comment]
Very much yes. I'm using node `v10.16.0`

```
$ npm -v
6.9.0
$ node -v
v10.16.0
```

**Comment by atla5** [comment]
Another thing you can try is to change the import method inside of the `main.js` from the npm-dependent one...
```
import 'primo-explore-unpaywall';
```

...to a local import that references the code inside of `node_modules` folder directly:
```
import '../node_modules/primo-explore-unpaywall/src/unpaywall.module';
```

Let me know if that helps

**Comment by scott-oit** [comment]
After upgrading Node.js I was able to upload to our sandbox. Thanks for all your help and time!

**Comment by atla5** [comment]
my pleasure! glad it worked out.
